
# ===========<---- COMENTARIO ---->===========#

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /data/jenkins  # Ajusta esto según tu entorno, esto es un ejemplo para local

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""


