#dar permisos (ejecutar desde la ec2)

#admin	Acceso completo en un namespace	Namespace
#edit	Permiso para modificar recursos dentro de un namespace	Namespace
#view	Acceso de solo lectura en un namespace	Namespace

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["watch","get","create", "delete", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io



